-- TABLE
CREATE TABLE CLIENTE(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR(80) NOT NULL,
Email VARCHAR(40) NOT NULL,
Telefone INTEGER
);
CREATE TABLE sqlite_sequence(name,seq);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
